CREATE DATABASE company;

CREATE TABLE DEPARTMENT (
    DNAME VARCHAR(10) NOT NULL,
    DNUMBER INT NOT NULL,
    MGRSSN CHAR(9) NOT NULL DEFAULT '000000000',
    MGRSTARTDATE DATE,
    PRIMARY KEY (DNUMBER),
    FOREIGN KEY (MGRSSN) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE EMPLOYEE (
    FNAME VARCHAR(15) NOT NULL,
    MINIT CHAR,
    LNAME VARCHAR(15) NOT NULL,
    SSN CHAR(9) NOT NULL,
    BDATE DATE,
    ADDRESS VARCHAR(30),
    SEX CHAR,
    SALARY DECIMAL(10, 2),
    SUPERSSN CHAR(9),
    DNO INTEGER NOT NULL,
    PRIMARY KEY (SSN),
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER),
    FOREIGN KEY (DNO) REFERENCES EMPLOYEE(SSN)
);

INSERT INTO EMPLOYEE (
    SSN, FNAME, LNAME, DNO, ADDRESS, BDATE, SALARY, SEX
) VALUES (
    '000000000', 'John', 'Smith', 1, '123 Some St', '1975-01-09', 30000, 'M'
);

INSERT INTO DEPARTMENT (
    DNUMBER, DNAME, MGRSTARTDATE
) VALUES (
    1, 'Management', '2022-05-07'
);

